version: '3.8'

services:
    postgres:
        build:
            context: ./dbase-service
            dockerfile: ./Dockerfile
        volumes:
            - /Education:/project/dbase-service/postgres.sql
        ports:
            - "3789:5432"
        environment:
            POSTGRES_PASSWORD: Aspireone533
            POSTGRES_DB: test-dbase
            POSTGRES_USER: test-user
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        healthcheck:
            test: pg_isready -d test-dbase -h postgres -p 5432 -U test-user
            interval: 6s
            retries: 4
            start_period: 2s
            timeout: 10s

    fast-api:
        build:
            context: ./service/
            dockerfile: ./Dockerfile
        depends_on: 
            postgres:
                condition: service_healthy
        volumes:
            - /Education:/project/service/main.py
        ports:
            - "5478:5478"
        environment:
            POSTGRES_PASSWORD: Aspireone533
            POSTGRES_DB: test-dbase
            POSTGRES_USER: test-user
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            APP_HOST: fast-api
            APP_PORT: 5478